### ISSUE TITLE
Support for fill_container

### ISSUE THREAD

**Issue by SorenHolm** [rianadon/timer-bar-card#104]
Having the option to use `fill_container: true` in a Mushroom setup would be nice. 

In this case, I'm using the timer-bar-card to show how long I've got before I have to wave my arms or a motion activated light turns off. 

In a big house with many areas/rooms, the only sane way to use the Mushroom light card is with `collapsible_controls: true` 

This means that when the light does turn on, the timer-bar-card on the right breaks my symmetry (Line 2 in the screenshot below). As opposed to another info-card  shown in line 4 in the screenshot. 

Being able to set `fill_container: true` would remedy that. 

I hope you'll consider this. 
Thank you for your effort either way.

Cheers, 
Søren

<img width="514" alt="Skærmbillede 2023-10-09 kl  11 57 29" src="https://github.com/rianadon/timer-bar-card/assets/1741169/4980bc7d-7efb-4244-9ed4-19569fec05df">

**Comment by rianadon** [comment]
This doesn't seem too hard to add. I'll have a look soon.

**Comment by SorenHolm** [comment]
Thank you :-)
