### ISSUE TITLE
Display remaining time in minutes

### ISSUE THREAD

**Issue by wookash** [rianadon/timer-bar-card#108]
Hello, great card! I'd like to be able to display remaining time in 'XX min' format. Is it possible?

**Comment by rianadon** [comment]
It is! `resolution: minutes` is what you're looking for.

**Comment by wookash** [comment]
hello, thank you, however, it does not work for me..

here's my card (I'm using mushroom slider and then with conditional enable your timer)

<img width="645" alt="image" src="https://github.com/rianadon/timer-bar-card/assets/222462/cf82a233-fc04-4d41-8269-17d886cee32c">

but it looks like this:

<img width="650" alt="image" src="https://github.com/rianadon/timer-bar-card/assets/222462/ac5de0b2-78f0-4776-9fad-390dcc9f88c0">

and card info:
`type: entities
card_mod:
  style: |
    ha-card {
      margin-bottom: 0px;
      max-height: 185px;
    }
entities:
  - type: custom:timer-bar-card
    entity: timer.timer_tv
    icon: mdi:timer-outline
    resolution: minutes
    bar_width: 100%
    bar_height: 12px
    bar_radius: 10px
    bar_direction: rtl
    invert: true
    debug: false
    name: []
    tap_action:
      action: call-service
      service: input_boolean.toggle
      service_data:
        entity_id: input_boolean.tv_sleep_toggle
    mushroom:
      layout: vertical
      color: blue
      secondary_info: none
    card_mod:
      style: |
        ha-card {
          background: none;
          --icon-size:54px !important;
          margin: -10px 0px -10px 0px;
          
        }
  - type: conditional
    conditions:
      - entity: timer.timer_tv
        state: idle
    row:
      type: custom:mushroom-number-card
      entity: input_number.slider_tv
      icon_type: none
      layout: vertical
      tap_action:
        action: none
      name: []
      card_mod:
        style: |
          ha-card {
            background: none;
            --control-height: 12px;
            margin-top: -30px;
            margin-bottom: 0px;
          }
          mushroom-state-info {
            background: none;
            margin-top: 7px;
            margin-bottom: -8px;
          }
show_header_toggle: false
title: TV timer target
state_color: false
`

**Comment by rianadon** [comment]
Ah I see what you mean. I can definitely add an option for this, maybe a format option where you can pass formats like `h:mm:ss` or `m min`

**Comment by wookash** [comment]
Perfect, thank you!

**Comment by TheZoker** [comment]
Yes that would be very welcome 🎉

**Comment by joergsti** [comment]
I have a long runnning timer (2 weeks) - It would be beneficial to display the remaining days

**Comment by rianadon** [comment]
This will be in the release today. The format will be using `%` for substitution, so you can do `%m min`, `%d days`, or combine them into `%H:%MM:%SS` (which is equivalent to the shorthand `hms`).

**Comment by wookash** [comment]
works as intended, thank you!
