### ISSUE TITLE
Bar from full to empty

### ISSUE THREAD

**Issue by kanedatatsaki** [rianadon/timer-bar-card#11]
Hi there,

a great Progress bar I use for the duration my Climate is running.
Due to the fact that it is a count down rather than a count up I'd love to have the option to have the progress bar run from full to empty.
That would be awesome.
Thanx for the great work.

**Comment by rianadon** [comment]
Thank you! I think this section might be what you're looking for: https://github.com/rianadon/timer-bar-card#receding-progress-bar
