### ISSUE TITLE
Could not convert duration

### ISSUE THREAD

**Issue by Bascht74** [rianadon/timer-bar-card#116]
**Describe the bug**
I am using a meater2 probe. I try to use the cook_time_remaining sensor.
The state is for example: `2023-12-24T14:24:10+00:00` (device_class: `timestamp`)
But it doesn't work!

It tried to use the 4th example:

> Set duration: { state: true }. This is less common for duration, but some integrations give the End Time as an entity with format like 2021-09-07T20:24:13+00:00 (you don't need units for start/end time).
> 
> duration:
>   state: true
> debug: true

Thx for any help, and: Merry Christmas!

**Your card configuration**
```yaml
type: custom:timer-bar-card
entity: sensor.meater_probe_1_cook_time_remaining
duration:
  state: true
debug: true
...
```

**Debug information**
<img width="480" alt="image" src="https://github.com/rianadon/timer-bar-card/assets/66269310/bf6e4a89-9e94-4b98-a53a-75391c1c6411">

**Comment by Bascht74** [comment]
I think I found it: 

```
type: custom:timer-bar-card
entity: sensor.meater_probe_1_cook_state
name: Verbl. Zeit
end_time:
  entity: sensor.meater_probe_1_cook_time_remaining
active_state:
  - Started
```

An example for the Meater (https://www.meater.com/) :-)

**Comment by rianadon** [comment]
Nice job! Sorry I missed you submitting this, but that looks like a correct configuration! You got it right that the confusingly named time remaining entity should go under `end_time`.

If you'd like to [submit an integration doc](https://github.com/rianadon/timer-bar-card/issues/new?template=tell-me-about-an-integration-you-got-working.md) for the Meater integration, I'd be more than happy to add it to the README.
