### ISSUE TITLE
Align Height for mushroom style cards in a row

### ISSUE THREAD

**Issue by skycryer** [rianadon/timer-bar-card#117]
I use 2 timer cards in a horizontal stack, appears also in a grid card. If 1 card is active and 1 is not then they do not fill the container when using the mushroom style. The mushroom cards have an option for fill_container that does not work here. 

Expected behaviour: Cards in a row should equal the height

<img width="484" alt="Screenshot 2023-12-27 at 10 40 22" src="https://github.com/rianadon/timer-bar-card/assets/3725699/b42200e3-7b78-4bc0-a3ff-d6ce01682e4d">

**Comment by rianadon** [comment]
The card now has support for `fill_container` like the mushroom cards, so it'll be possible to match the heights with the latest version.
