### ISSUE TITLE
HA 2024.02.0b1 onwards: entity icon not displayed in Mushroom Styling

### ISSUE THREAD

**Issue by ResteNarquois** [rianadon/timer-bar-card#126]
**Describe the bug**
Entity icon is not displayed when using Mushroom Styling. Seems to be connected to frontend changes introduced with HA 2024.02.0. Reverting to 2024.01.6 fixes the issue.

![Untitled3](https://github.com/rianadon/timer-bar-card/assets/51411528/4f8436e7-2295-419a-9ebb-5ddbe40b18de)

I do have card_mod installed, but above screenshot is with default HA light theme, with all card_mod theme classes and customisations disabled.

Maybe this recent PR for Mushroom is relevant? (mentions change to icon logic in 2024.02):

[https://github.com/piitaya/lovelace-mushroom/pull/1342](url)

Looking at the DOM, there is now an empty shadow-root after ```ha-state-icon``` where ```ha-svg-icon``` used to be:

![Untitled](https://github.com/rianadon/timer-bar-card/assets/51411528/31883f29-2544-4eed-a6ac-b108d1aeae2e)

**Your card configuration**
```yaml
- type: custom:timer-bar-card
  entity: timer.study_motion_sensor
  mushroom:
```

**Debug information**
![Untitled2](https://github.com/rianadon/timer-bar-card/assets/51411528/1dccfa85-37af-42bd-b39e-ba75f0f7a4e7)

**Comment by rianadon** [comment]
![Not again](https://media1.tenor.com/m/58rVrcSfwCcAAAAC/panda-oh-no.gif)

> Maybe this recent PR for Mushroom is relevant? (mentions change to icon logic in 2024.02):
> [https://github.com/piitaya/lovelace-mushroom/pull/1342](https://github.com/rianadon/timer-bar-card/issues/url)

This looks very relevant. Looks like I'll be making a release this weekend.

**Comment by PablaV** [comment]
Bumping this, running 2024.2.2 and the icons are still not showing up for mushroom style but do show up when using regular style

**Comment by rianadon** [comment]
Thanks for pinging me on this. Release coming today!
