### ISSUE TITLE
Mushroom theme changes

### ISSUE THREAD

**Issue by jhemak** [rianadon/timer-bar-card#128]
Following recent updates to the Mushroom cards, the font weight of timer bar card in Mushroom mode no longer matches.  The Name and time remaining both appear more bold than the primary and secondary text on all other mushroom cards.

I was able to use card_mod as a workaround until you are able to update the source code (wish I knew how to do that to help you out!)

```
card_mod:
    style: |
      ha-card {
        --card-primary-font-weight: var(--mush-card-primary-font-weight, 500);
        --card-secondary-font-weight: var(--mush-card-secondary-font-weight, 400);
        --secondary-text-color: var(--mush-card-secondary-color, var(--primary-text-color));
      }
```

**Comment by rianadon** [comment]
Thanks for this! I'll take a look when I have some time.
Looks like the mushroom cards and Home Assistant tile cards might finally have consistent font weights?

**Comment by Slalamander** [comment]
To add to this (at least I think it's related), certain customization options also seem to have broken, at least when using the mushroom style in horizontal mode. For example:
```
type: custom:timer-bar-card
entity: timer.was
bar_width: 50%
mushroom:
  layout: vertical
```
Gives this card:
![image](https://github.com/rianadon/timer-bar-card/assets/103532133/abd5aee7-c5da-40a8-8868-8071bc30cf3e)

But when using this configuration:
```
type: custom:timer-bar-card
entity: timer.was
bar_width: 50%
mushroom:
  layout: horizontal
```
It results in this layout:
![image](https://github.com/rianadon/timer-bar-card/assets/103532133/0a189580-d4fd-42b9-8dfc-a82d2c678177)

Considering

**Comment by rianadon** [comment]
As you found in #115, I don't think `bar_width` was ever something that worked with the mushroom layout. `text_width` is what you should use to give the time left some more room to breath.

Please do open a new one for `bar_radius` and `bar_height`. I'm surprised that `layout: hide_name` even changes anything. It was not my intention for `layout` to be a usable option with mushroom cards.

**Comment by Slalamander** [comment]
I was opening the issue and playing around with the config, but it seems like it may have been the card preview not updating? I wasn't able to replicate it at least, and I've had issues with that before. I thought I saved them though, but alas.

**Comment by rianadon** [comment]
Fixed in d3e243c911c77f6308bbb2a1b670a4691f937c32.

**Comment by rianadon** [comment]
Thanks for catching that. It looks like there were a few more styles I needed to update. It should be fixed with the new release.

**Comment by jhemak** [comment]
Looks good now!  Thanks again!
