### ISSUE TITLE
Use the bar to show battery % (state of Charge)

### ISSUE THREAD

**Issue by corvy** [rianadon/timer-bar-card#141]
I am trying to use this excellent card to show a battery percentage for the "house" batteries of a boat. 

![image](https://github.com/rianadon/timer-bar-card/assets/138292/497f1a0f-43c7-4379-afa3-8b3ce7a4888b)

But I get no progress bar. Should this not work "out-of-the-box" kindof? I use the card for a timer, and there it works just perfectly! 

This is my sensor:
![image](https://github.com/rianadon/timer-bar-card/assets/138292/a1fdb1c3-c21b-42e4-b822-7e5772ce1788)

Any pointers? 👯

**Comment by rianadon** [comment]
The card is really only meant for timers (i.e. things that are counting down one tick per second) and not percentages (i.e. things that change but not based on any clock). I had a design going for how I could adjust the options to support these types of things but never had time to finish.

Maybe one day I'll add support for these kinds of things. Maybe you can hack something together with `remain_time`, but even if you encode your battery as "85.6" seconds, one second later the progress bar is going to show "84.6".

**Comment by corvy** [comment]
Ok thanks. :) I will look elsewhere to find a solution. Thanks for responding!
