### ISSUE TITLE
LG ThinQ Washer/Dryer Data not working

### ISSUE THREAD

**Issue by iDVB** [rianadon/timer-bar-card#15]
First off, amazing card you have here. I'm just new to it and seem to be unable to get it working with my Device entities.

I use the [LG ThinQ HACS integration](https://github.com/ollo69/ha-smartthinq-sensors) to get my Washer and Dryer data.
The Dryer looks like this...
![image](https://user-images.githubusercontent.com/189506/127088643-ea0d7f0c-2911-4e7d-905d-c0198f89f20d.png)

It appears each needed bit of data is in a separate entity. It seems in order to plot an accurate progress bar you would need two entities:
`sensor.dryer_remain_time`  =  `0:07`
and
`sensor.dryer_initial_time` = `0:20`

The next problem is that these times are written in the `m:s` format which there doesn't seem to be support for. 

Perhaps, adding support for defining a template for the calculation and maybe a format string to define the format the values are coming in as.

**Comment by rianadon** [comment]
Ahahha thank you! You ask for a lot.

You should already be able take data from other entities: see [this section](https://github.com/rianadon/timer-bar-card/issues/15). I'm reluctant to add in templating because that requires a lot more code, and Home Assistant itself already has so much templating power.

Since this integration is wacky, how about using the [template integration](https://www.home-assistant.io/integrations/template/)?

I haven't tested this, but something like the following might work for you:

```yaml
template:
  - sensor:
      - name: "Dryer Timer"
        state: "{{ states('sensor.dryer') }}"
        attributes:
          duration: "0:{{ states('sensor.dryer_initial_time') }}" # 0: in front to format the time correctly
```

As long as the template picks up state changes, its `last_changed` property should be accurate, which means you don't need the remaining time.

**Comment by iDVB** [comment]
Thanks @rianadon ! i thought there must be some kinda template solution outside of the card but not familiar with that. If it updates, should work fine. 

Oh, and I guess the `last_changed` will carry the value when it was last changed? Let me give this a try. Cheers!

**Comment by rianadon** [comment]
Let me know if it works!

And if you do get it working and you're down to create a pull request, I'd love to add this to the examples!

**Comment by kareem613** [comment]
Looks like the LG integration has since changed. This is what the attributes look like with `debug:true` 

`Attr: {"run_completed":"off","error_state":"off","initial_time":"0:29","remain_time":"0:10","reserve_time":"0:00","current_course":"Normal","run_state":"Rinsing","pre_state":"Washing","error_message":"-","spin_speed":"High","water_temp":"Warm","dry_level":"Not Selected","tubclean_count":"41","remote_start":"on","door_close":"on","child_lock":"off","steam":"off","pre_wash":"off","turbo_wash":"on","friendly_name":"Washer","icon":"mdi:washing-machine","supported_features":3}`

I think the issue here is the `initial_time` is the total time for the timer. ie. There are no timestamps. 
`remaining_time` is already calculating how much time is left. 

Is this usable without having timestamps?

**Comment by rianadon** [comment]
You can totally set the card up configuring only `initial_time` as `duration`, but then the start time will be calculated at the mercy of whenever the washer changes state, so you may or may not have success.

It would be really nice if that integration gave timestamps.

**Comment by lcavalli** [comment]
I asked the LG SmarthingQ integration maintainer and he kindly updated the integration adding the seconds to time attributes in version 0.12.3.

**Comment by mortalone** [comment]
Hi. did anyone find a solution to this issue ?

i have the same problems. i cannot get the bar to show. and i have tried the suggestions listed in here. but i might do it wrong.

**Comment by funtastix** [comment]
> You can totally set the card up configuring only `initial_time` as `duration`, but then the start time will be calculated at the mercy of whenever the washer changes state, so you may or may not have success.
> 
> It would be really nice if that integration gave timestamps.

I've had the same issue. I've created a pull request: https://github.com/rianadon/timer-bar-card/pull/47 to fix that LG integration for me.

**Comment by rianadon** [comment]
Now that #47 has just landed in the codebase, it's possible to use the card with the integration. The `remain_time` option will automatically identify the LG device's attribute, so it doesn't need configuring.

All you need is:
```yaml
type: custom:timer-bar-card
duration:
  attribute: initial_time
```

I'm sorry it took so long for me to merge the PR.

**Comment by BillyFKidney** [comment]
I have tried using duration and remaining but the card still appears like this:
<img width="702" alt="image" src="https://github.com/rianadon/timer-bar-card/assets/65253277/ae4ba21d-f3d1-4cb9-b4c4-0d5cb339a712">

```
type: custom:timer-bar-card
entity: sensor.washer_remaining_time
duration:
  attribute: initial_time
```

Am I using the wrong entity?
<img width="560" alt="image" src="https://github.com/rianadon/timer-bar-card/assets/65253277/019db3c4-6d5c-438e-9022-e6c36bc52835">
<img width="552" alt="image" src="https://github.com/rianadon/timer-bar-card/assets/65253277/d851dbdc-640b-42fa-8390-af288207fa47">
<img width="316" alt="image" src="https://github.com/rianadon/timer-bar-card/assets/65253277/b6442964-f496-4c7b-a700-7c99b48fc09e">

Do I need to enable `sensor.washer_countdown_time`?

**Comment by liyuxuan7762** [comment]
Hello there, I am very new to HA, could you tell me how to config the initial time? 

![Image](https://github.com/user-attachments/assets/77755e5c-ca93-4364-97af-5f1939fb3133)

**Comment by Johnqjx** [comment]
Same here. All it does is show the timestamp.

type: custom:timer-bar-card
entity: sensor.lg_front_load_washer_remaining_time
end_time:
   state: true
debug: true


![Image](https://github.com/user-attachments/assets/70416283-844e-448f-89c0-7796afd3491d)

**Comment by BillyFKidney** [comment]
> Same here. All it does is show the timestamp.
> 
> type: custom:timer-bar-card entity: sensor.lg_front_load_washer_remaining_time end_time: state: true debug: true
> 
> ![Image](https://github.com/user-attachments/assets/70416283-844e-448f-89c0-7796afd3491d)

Amazingly things my timer card has been super easy and worked through the last few versions of the LG Integration.

```
type: custom:timer-bar-card
entity: sensor.washer
duration:
  attribute: initial_time
bar_direction: rtl
invert: true
bar_height: 20px
mushroom: null
bar_radius: 10px
hold_action: none
tap_action: none
double_tap_action: none
```

**Comment by MathisP75** [comment]
Same for me here, no bar showing

**Comment by MathisP75** [comment]
I figured it out. You need to set the entity to the generic washer entity, for some reason. In my case `  - entity: sensor.front_load_washer`:

```
type: custom:timer-bar-card
entities:
  - entity: sensor.front_load_washer
    duration:
      attribute: sensor.front_load_washer_initial_time
    remaining:
      attribute: sensor.front_load_washer_remaining_time
debug: false

```

**Comment by teamster22** [comment]
> I figured it out. You need to set the entity to the generic washer entity, for some reason. In my case ` - entity: sensor.front_load_washer`:
> 
> ```
> type: custom:timer-bar-card
> entities:
>   - entity: sensor.front_load_washer
>     duration:
>       attribute: sensor.front_load_washer_initial_time
>     remaining:
>       attribute: sensor.front_load_washer_remaining_time
> debug: false
> ```

For the life of me, I can't seem to figure out what "set the entity to the generic washer entity" means here. I have my sensors named with the syntax "sensor.clothing_washer_remaining_time" etc, and don't have one for just "sensor.clothing_washer" as best I can tell. So when I try to use the syntax provided here, I get this

![Image](https://github.com/user-attachments/assets/11631d1a-633e-4f05-a0d6-049fbce014e4)

**Comment by rDogge** [comment]
> I figured it out. You need to set the entity to the generic washer entity, for some reason. In my case ` - entity: sensor.front_load_washer`:
> 
> ```
> type: custom:timer-bar-card
> entities:
>   - entity: sensor.front_load_washer
>     duration:
>       attribute: sensor.front_load_washer_initial_time
>     remaining:
>       attribute: sensor.front_load_washer_remaining_time
> debug: false
> ```

THIS!!
Thank you very much, i searched for this all morning
thank you
