### ISSUE TITLE
Question, request maybe - CSS

### ISSUE THREAD

**Issue by kajmaj** [rianadon/timer-bar-card#17]
Does the card accept styles (CSS)?
I would like to change font but not able to achieve it somehow.

BTW nice and neat card, great thank you

**Comment by rianadon** [comment]
Thank you! The card does not have support for custom css built in, but you may be able to use the [card-mod](https://github.com/thomasloven/lovelace-card-mod) plugin.

**Comment by kajmaj** [comment]
Thanks for pointing me to the right direction.
This one works :-)

```
              - type: custom:mod-card
                card_mod:
                    style: |
                      ha-card {
                        font-variant: small-caps;
                       }
                card:  
                    type: custom:timer-bar-card
                    entity: timer.cycle1_zone_duration
                    name: Zóna
                    compressed: true
```
