### ISSUE TITLE
Unsupported remaining time format for Home Connect alt

### ISSUE THREAD

**Issue by SebRut** [rianadon/timer-bar-card#172]
I'm trying to use the card for my washer/dryer with data coming from the Home Connect Alt integration. The integration exposes an "estimated remaining program time" sensor in the format "hh:mm" which seems to be incompatible with `duration` and `remain_time` because of the missing seconds component.
Is there a way to configure the card to use the data from the sensor, or do I need some sort of template sensor to achieve this?

**Integration name and link**
Home Connect Alt - https://github.com/ekutner/home-connect-hass

**Comment by rianadon** [comment]
Yes, you would need to use a template or template card to correct the time. I'm strict with the allowable inputs to the card since Home Assistant uses only the `hh:mm:ss` format, but trying to keep up with the formats every custom integration is using would be too much work.
