### ISSUE TITLE
Explicitely set duration

### ISSUE THREAD

**Issue by override80** [rianadon/timer-bar-card#4]
Hi, I've been waiting for this since you posted the mock on reddit! Thankyou!

Just one question, I would like to attach this to a switch activated via scheduler card or automation. I do not have any duration attribute, but the switch will turn off in 60 minutes. 

Is there any way to sey duration via yaml or do I need to set up a fake timer? I prefer this component over bar-card since it updates continuously.

**Comment by rianadon** [comment]
There isn't any way to set duration via yaml now, but this is something I've been meaning to implement for a while, so I'll get to it!

**Comment by override80** [comment]
Thankyou!

**Comment by rianadon** [comment]
Done and [documented](https://github.com/rianadon/timer-bar-card#use-with-unsupported-entities). Please reopen if this doesn't work!
