### ISSUE TITLE
New Customization option border-radius for bar

### ISSUE THREAD

**Issue by snipestyle9410** [rianadon/timer-bar-card#40]
It would be great, if we can get an option to define a border-radius for the bar.
Something like: bar_border-radius: 10px would be awesome!

**Comment by rianadon** [comment]
This is a reasonable request. I'll put this in the next release!

**Comment by rianadon** [comment]
In v1.17!

**Comment by snipestyle9410** [comment]
Can confirm that it is working! Thank you very much!
