### ISSUE TITLE
full_row + icon

### ISSUE THREAD

**Issue by sblogoshs** [rianadon/timer-bar-card#52]
Hi.

full_row: true and an icon without a title or name would be nice.

Greetings, Stefan

**Comment by Hannah-Bee** [comment]
Something like that
![Screenshot_20220715-210741_Home Assistant](https://user-images.githubusercontent.com/84235452/179294871-5f45346f-93fc-4041-9330-935ffc5c88c3.jpg)

Try translation with empty string

-entity: input_boolean.bool_rasen_1_einzeln
type: custom:timer-bar-card
invert: true
layout: hide_name
duration:
  entity: input_number.input_dauer_rasen_1
  units: minutes
icon: mdi:timelapse
bar_radius: 5px
translations:
        'off': ' '

**Comment by sblogoshs** [comment]
Great, that's how it works!

Thank you

Greetings, Stefan
