### ISSUE TITLE
Feature request - inverted progress

### ISSUE THREAD

**Issue by Plawasan** [rianadon/timer-bar-card#6]
Hello,

hopefully something pretty quick to implement - I would appreciate the option to change the direction of the progress bar, i.e. instead of a blue bar extending from left to right make it a blue bar retracting from right to left.

Thanks!

**Comment by rianadon** [comment]
I might not need to implement anything. Does inverting the foreground and background colors achieve what you want?

```
type: custom:timer-bar-card
bar_foreground: "#eee"
bar_background: "var(--mdc-theme-primary, #6200ee)"
```

**Comment by Plawasan** [comment]
I have considered that, but that would not change the direction of the progress bar, it would still run right to left.. For some reason i can't really explain LTR makes more sense to me :)

**Comment by rianadon** [comment]
Thanks! I get it now!

**Comment by rianadon** [comment]
After upgrading to v1.4, this should do what you want:

```yaml
bar_direction: rtl
bar_foreground: "#eee"
bar_background: "var(--mdc-theme-primary, #6200ee)"
```
