### ISSUE TITLE
Miele washing machine

### ISSUE THREAD

**Issue by dagmoen** [rianadon/timer-bar-card#62]
Hi, I've tried to get a progress bar for my Miele washing machine. But I've been unable to get it to work.
Are you able to help me to figure it out? I've tried creating a template sensor but I was unable to get it to work.
The remaining/duration is in minutes, and the start and endtime is in hh:mm.

![image](https://user-images.githubusercontent.com/10994979/204099604-ba4cc159-b574-4306-bb78-cf25750634b3.png)

**Comment by rianadon** [comment]
It's not your fault you've been unable to get the card to work with your washing machine. Based on these entities, there's no way to use the card without resorting to creating a template sensor.

The card expects the start and end times to be full formatted dates—this way it can handle multi-day timers correctly. Your entities do not have dates in them, so a template sensor would need to insert the current date in front of the `finish_at` and `started_at` times.

I'll write up more later. I need to refresh myself on how templates work.

However, if you know the washing machine will always run for a set duration, you can use the `duration: { fixed` option and the `washing_machine_remaining_time_2` sensor to get a working timer.

**Comment by dagmoen** [comment]
Hi, thanks for helping. The duration can vary depending on the program etc.
This is my attempt to creating the template sensor, but I couldn't get it to work.

`template:
  - sensor:
    - name: "Washing machine timer"
      state: "{{ states('sensor.washing_machine_status_2') }}"
      attributes:
        duration: "{{ states('sensor.washing_machine_elapsed_time_2') }}"
        start_time: "{{ states('sensor.washing_machine_started_at') }}:00"
        end_time: "{{ states('sensor.washing_machine_finish_at') }}:00"
        remaining: "{{ states('sensor.washing_machine_remaining_time_2') }}"`

**Comment by rianadon** [comment]
Thanks for writing what you have! You should only need `start_time` and `end_time`, but they need to have the full date in them. Try this template:


```yaml
sensor:
  name: "Washing machine timer"
  state: "{{ states('sensor.washing_machine_status_2') }}"
  attributes:
    start_time: "{{ now().strftime('%Y-%m-%dT') + states('sensor.washing_machine_started_at') }}:00"
    end_time: "{{ now().strftime('%Y-%m-%dT') + states('sensor.washing_machine_finish_at') }}:00"
```

**Comment by dagmoen** [comment]
Excellent! It worked! Love the card, will implement it for my dryer and dish washer as well :)

![image](https://user-images.githubusercontent.com/10994979/205309858-b6f92d97-ace5-484b-8608-0edbc263e8ab.png)
![image](https://user-images.githubusercontent.com/10994979/205309973-e34ca9ec-23f1-4b40-97bc-bb0639608149.png)

Thanks! :)

**Comment by rianadon** [comment]
Wonderful! I'm glad it works! I'll add Miele to the list of integrations on the readme.

Also since the washing machine runs for over an hour, I'd recommend you give the remaining time some more space with the `text_width: 4.5em` option. That should make the card look a little less cramped 🙂

**Comment by Razsmithii** [comment]
Hello, here a testet template for using a Miele tumbler together with the Miele integration:

In sensors.yaml:
`- platform: template
  sensors:
    trockner_timer_3:
      value_template: "{{ states('miele.trockner') }}"
      attribute_templates:
        start_time: "{{ now().strftime('%Y-%m-%dT') + states.sensor.trockner_status.attributes.kickoffTime + ':00' }}"
        end_time: "{{ now().strftime('%Y-%m-%dT') + states.sensor.trockner_status.attributes.finishTime + ':00' }}"`

Here the configuration for the card itself:

`type: custom:timer-bar-card
entity: sensor.trockner_timer_3
name: Trockner
active_state: In Betrieb
icon: mdi:tumble-dryer
debug: false
guess_mode: false
text_width: 4.5em
bar_radius: 4px
bar_width: 40%`

**Comment by rianadon** [comment]
@Razsmithii thank you for posting the template and config! I've edited your comment to include the code block formatting.

**Comment by pille89** [comment]
Hello,

when I create the following sensor:

```javascript
 - sensor:            
    - name: "washing_machine_timer"
      state: "{{ states('sensor.washing_machine_status') }}"
      attributes:
      start_time: "{{ now().strftime('%Y-%m-%dT') + states('sensor.washing_machine_starte_um') }}:00"
      end_time: "{{ now().strftime('%Y-%m-%dT') + states('sensor.washing_machine_ende_um') }}:00"
``` 

I get the following error message:

```javascript
Logger: homeassistant.config
Source: config.py:505
First occurred: 10:22:18 (1 occurrences)
Last logged: 10:22:18
Invalid config for [template]: expected a dictionary for dictionary value @ data['sensor'][0]['attributes']. Got None extra keys not allowed @ data['sensor'][0]['end_time']. Got "{{ now().strftime('%Y-%m-%dT') + states('sensor.washing_machine_ende_um') }}:00" extra keys not allowed @ data['sensor'][0]['start_time']. Got "{{ now().strftime('%Y-%m-%dT') + states('sensor.washing_machine_starte_um') }}:00". (See /config/configuration.yaml, line 232). 
``` 

![2023-11-30_11h00_24](https://github.com/rianadon/timer-bar-card/assets/88047389/803c6320-3b94-4053-a7a0-988a8dc61b82)

![2023-11-30_11h01_34](https://github.com/rianadon/timer-bar-card/assets/88047389/267c838a-2065-4087-9452-101645a93436)

**Comment by rianadon** [comment]
It looks like it might be an error with the indentation?
The `start_time` and `end_time` underneath `attributes` in the YAML you posted should be indented by a few more spaces (at least two).

**Comment by markusby** [comment]
Hi There,
can someone mybe help me, as I'm not getting the Miele dishwasher in the time.bar integrated?

I added in the config.yaml the folloing sensor:

    sensor:
      - name: Dishwasher_Time
        unique_id: dishwasher_time
        state: "{{ states('sensor.dishwasher_status') }}"
        attributes:
          start_time: "{{ now().strftime('%Y-%m-%dT') + states('sensor.dishwasher_started_at') }}:00"
          end_time: "{{ now().strftime('%Y-%m-%dT') + states('sensor.dishwasher_finish_at') }}:00"


sensor.dishwasher_status:
![image](https://github.com/rianadon/timer-bar-card/assets/17511195/b44e3093-80b1-4141-b247-6547d13e66d1)

sensor.dishwasher_started_at
![image](https://github.com/rianadon/timer-bar-card/assets/17511195/a47c3808-3b43-4f11-834f-3b086358c526)

sensor.dishwasher_finish_at:
![image](https://github.com/rianadon/timer-bar-card/assets/17511195/b3a0086f-ff39-4f62-8fc6-6a1ea00cee67)

**But somehow it status can not be read incl. start/end time**
![image](https://github.com/rianadon/timer-bar-card/assets/17511195/0fb1de78-a53d-4afd-86d7-f211f3a73b33)

Any ideas I can look into would be appreciated.
Markus

**Comment by zhelyan** [comment]
@runeix a bit late but you need to make sure that the value of `active_state` matches what's returned by the sensor

In my case, I have `active_state: running`

**Comment by Roemer** [comment]
Hello all

I also did an approach with a Miele timer.

My main difference is that I use UI-created sensors (which I think are easier to maintain and adjust) instead of the yaml-created template sensor.

So I created a `combination sensor` (`Kombinationssensor`) as a `sum` to add the remaining time and the elapsed time together (which should give the total duration).
This looks like this:
![Image](https://github.com/user-attachments/assets/3362343b-0be5-428f-b439-143878472a30)

The card then in the end can simply use this new total time as `duration` and use the `remaining time` as `remain_time`:
```yaml
type: custom:timer-bar-card
entity: sensor.dishwasher_status
active_state: running
duration:
  entity: sensor.geschirrspuler_total_zeit
  units: minutes
remain_time:
  entity: sensor.dishwasher_verbleibende_zeit
  units: minutes
text_width: 4em
```
Also don't forget to add the `active_state` which was `running` for me.

**Comment by crazyfraggle** [comment]
Adding a comment here since I ran into the same issue as @Roemer with my new dishwasher, but the solution above did not work out of the box.

I set up a combined sensor like above:

<img width="591" height="682" alt="Image" src="https://github.com/user-attachments/assets/64a496aa-1ffc-45ae-9628-2f5f4a7b715a" />

But I kept getting warnings about wrong units whenever the machine was idle. I fixed this with the following hack:

1. Create a number entity with value 0:

  <img width="536" height="458" alt="Image" src="https://github.com/user-attachments/assets/97c2ad75-4abf-475c-b135-8d21178a8bee" />

2. Use this to enforce the type for *both* remaining time and the calculated total time.

<img width="594" height="505" alt="Image" src="https://github.com/user-attachments/assets/f2fcc3d8-cfc4-408e-b98f-ab7b82b0fa64" />

<img width="577" height="505" alt="Image" src="https://github.com/user-attachments/assets/60371039-d54c-4bf0-9cbd-caac328313fa" />

3. Use these values in the Timer bar card

```yaml
type: custom:timer-bar-card
entities:
  - sensor.dishwasher
active_state: in_use
duration:
  entity: sensor.dishwasher_total_time2
  units: minutes
remain_time:
  entity: sensor.dishwasher_remaining_time3
  units: minutes
text_width: 4em
layout: full_row
```
