### ISSUE TITLE
[Feature Request] tap_action

### ISSUE THREAD

**Issue by Ulrar** [rianadon/timer-bar-card#63]
Hi,

This looks great, first of all.
That said I may have missed it but I don't see an option to toggle the timer from the card, is there any way to do so ?

If not I think adding a tap_action (and hold and double tap maybe, although I have less use for it myself) like the mushroom cards have would be a great addition. We could then just use that to do a call-service and start / stop the timer, or toggle it.

**Comment by Ulrar** [comment]
Just realized that adding tap_action actually works fine, I just assumed it wouldn't because it's not in the readme and there's no visual editor.
Nevermind then, all good !

**Comment by rianadon** [comment]
Glad you figured it out! You probably didn't notice, but if you expand the configuration options in the README, buried at the bottom is a sentence saying the card supports actions.

But you are very correct this could be explained a lot clearer. I'll remove this text from under the expanding menu so it's easier to notice.
