### ISSUE TITLE
Idle translation

### ISSUE THREAD

**Issue by julienlarivee** [rianadon/timer-bar-card#7]
Hi,

When an idle timer is set in a entity card, I got the text "En veille" displayed since my language is set to french.
Would it be possible to translate it in your card too?

![image](https://user-images.githubusercontent.com/55027006/123297341-7de9b680-d4e5-11eb-96c3-ad93d556cafe.png)

Thank you. Great card by the way!

**Comment by julienlarivee** [comment]
Sorry, just found the example :

translations:
      idle: Gas, gas, gas!

**Comment by rianadon** [comment]
I know you've found your solution, but to spare you more effort the version I've just released (v1.4) will use Home Assistant's translation dictionary, so the states will automatically be translated to french 😄

**Comment by metbril** [comment]
Unfortunately, `idle` is not translated into Dutch when using the Mushroom cards. See also #145 for a screenshot. Should I create a new issue, or will you reopen this one?
