### ISSUE TITLE
Add  start_time support for... a timer 

### ISSUE THREAD

**Issue by Luth1ng** [rianadon/timer-bar-card#70]
Hello there,

Glad to discovered this nice card today.
I am trying to configure this card for a ThinQ dish washer.
It seems to work great for the remaining time of the current washing process, but it doesn't seem to work for a scheduled one.

What I would like to have is :
One progress bar which displays next scheduled washing if there's any, or displays remaining time for current washing.

I tried the following configuration :
```
type: custom:timer-bar-card
entity: sensor.lave_vaisselle
state_attribute: process_state
active_state: "Lavage"
waiting_state: "En attente"
duration: {attribute: initial_time}
start_time:
  entity: sensor.lave_vaisselle_countdown_time
  units: hours
debug: true
```
which results in : 

```
Lave-Vaisselle
Scheduled for Invalid Date
State: on (state mode = waiting)
Mode: waiting (auto mode = N/A, unused)
Duration: 11760 second
Time remaining: 11760
Counter: 11760
Did you set active_state? Attr: {"run_completed":"off","error_state":"off","initial_time":"3:16:00","remain_time":"3:16:00","reserve_time":"1:56:00","current_course":"Intensif","run_state":"Lavage","process_state":"En attente","half_load":"off","error_message":"-","tubclean_count":"34","auto_door":"off","child_lock":"off","delay_start":"on","door_open":"off","dual_zone":"off","energy_saver":"off","extra_dry":"on","high_temp":"on","night_dry":"off","rinse_refill":"off","salt_refill":"off","icon":"mdi:dishwasher","friendly_name":"Lave-Vaisselle"} 
```

I guess the start_time value wasn't made for a timer (like 1:56:00) but for a specific event time (like 2021-09-07T20:24:13+00:00)

Could you add this feature please ?

Many thanks !

**Comment by rianadon** [comment]
This sounds like a great idea, but adding another method to specify start times would add a lot of complexity to the card.
I'd rather that the ThinQ integration give a `start_time` in the full date format.

I will see if I can submit a PR to the integration.

**Comment by Luth1ng** [comment]
Thanks for your quick reply.
Nice, let me know if need any help !

I thought this would be easy as you could just have a function to get current date and then just add the "delay" but it may be more complex indeed.

Keep us informed please :)

**Comment by rianadon** [comment]
Now that the PR is merged, you should be able to use a simple config like:

```yaml
type: custom:timer-bar-card
entity: sensor.lave_vaisselle
state_attribute: process_state
active_state: "Lavage"
waiting_state: "En attente"
debug: true
```

Let me know if there are any issues!
