### ISSUE TITLE
Possibility to configure timer resolution

### ISSUE THREAD

**Issue by jensrossbach** [rianadon/timer-bar-card#75]
Hello,

I would like to have the possibility to configure the resolution/granularity of the timer. I'm using the timer bar card to display the progress of my dishwasher and my washing machine. But for these devices, I don't need seconds granularity as the duration of the programs is anyway in the range of one to several hours. It would be totally sufficient to have a resolution of minutes. Therefore, could you add an option to set the timer granularity? It would also help with the space used on the card for the display of the remaining time because in case of minutes resolution, you have no seconds and you could still use a form with two parts like "hh:mm".

Best regards,
Jens

**Comment by rianadon** [comment]
Great idea! I should've thought of this long ago.

**Comment by igorsantos07** [comment]
Same here. My suggestion would be to show seconds only when less than 60min, so you always end up with two time pieces. I wonder if it's worthy to have a setting for that (so it's not a breaking change) or something that could be the default (really, no need of seconds at all when you're seeing a timer that spans more than an hour....... right?)

**Comment by bphirsh** [comment]
+1, was also looking to hide seconds for my 4-hours of air purification.

**Comment by rianadon** [comment]
> Same here. My suggestion would be to show seconds only when less than 60min, so you always end up with two time pieces. I wonder if it's worthy to have a setting for that (so it's not a breaking change) or something that could be the default (really, no need of seconds at all when you're seeing a timer that spans more than an hour....... right?)

Good suggestion! I think having a setting to switch between a resolution of seconds/minutes/automatic would be a great idea. Personally I worry about automatic since at first glance it's unclear whether the timer is in minutes or seconds, but after a few seconds you'd know.
