### ISSUE TITLE
Right to Left Option seems to not work ?

### ISSUE THREAD

**Issue by holdestmade** [rianadon/timer-bar-card#8]
Installed v 1.5, using this config:

```
        - type: custom:timer-bar-card
          entity: timer.filament_dryer_duration
          name: Timer
          state_color: true
          bar_direction: rtl
          bar_foreground: '#eee'
          bar_background: 'var(--mdc-theme-primary, #6200ee)'
```

using ltr and rtl makes no difference, have tried reload and refresh

Thanks

**Comment by rianadon** [comment]
But it works for me.....

![recording2](https://user-images.githubusercontent.com/18223213/123391270-aeb30580-d550-11eb-91b4-1f7f4fe0fe9e.gif)

Maybe the browser cache is just being stubborn?

**Comment by holdestmade** [comment]
Yes that was it. CTRL F5 didn't work, had to go to dev tools and hard refresh

Cheers
