### ISSUE TITLE
Allow state to be a numeric value

### ISSUE THREAD

**Issue by chriswood1001** [rianadon/timer-bar-card#81]
I have a manual sensor for which I'd like the state to be my remaining time, such as "5" with a unit of "min". However, timer-bar-card requires a specific "active_state" such as "on" or "running".

Suggestion to allow an "active_state_not".

**Comment by rianadon** [comment]
Do you have both a start and end time you can fetch for the manual sensor? You could then use `guess_mode`, and then you don't need to specify an `active_state`.

I hate to complicate the setup even more with an `active_state_not`, but if that's the logical way to solve configure your sensor then I'll add it.

**Comment by chriswood1001** [comment]
Using `guess_mode` solved this scenario. Thank you for the workaround solution.

**Comment by rianadon** [comment]
Awesome! Glad it worked.
