### ISSUE TITLE
Integrate deeper with automations/scripts which run delays

### ISSUE THREAD

**Issue by igorsantos07** [rianadon/timer-bar-card#82]
Right now, the suggestion to integrate with automations/scripts is to manually set the fixed time it takes to run. It's easy and straightforward, but it's repetitive and prone to issues when you change the automation.

I noticed the script includes the following attributes, which could be worked out to avoid using the fixed time:
```yaml
last_triggered: 2023-06-19T20:14:09.518310+00:00
last_action: delay 2:00:00
```

If it identifies the entity as a script, which main state is `on`, and the script has the `last_action` as `delay: H:MM:SS`, then we have the duration :)

**Comment by rianadon** [comment]
Wow that's handy! I'll add this to the next version.

However, only scripts seem to add the `last_action` attribute. The automations only have the `last_triggered`, so unfortunately this will only work for scripts.

**Comment by igorsantos07** [comment]
Just created an automation with a timer and was coming here to tell you exactly that. It's sad :(

I also had a hard time trying to fit a `timer` into my workflows (yep, I'm working on these since before I came here to report you that lol), and [kind Taras helped me](https://community.home-assistant.io/t/frustration-how-to-set-mutually-exclusive-timers-solved-change-a-single-timer-with-timer-start/583780) seeing it's probably wiser to manipulate a separate `timer` entity if the person wants to display the time left from an automation.

**Comment by rianadon** [comment]
I took a quick look over your thread, and it gave me an idea of how this card could integrate with ~~automations~~ scripts. It's a very common use case for the card, so I'll work on providing a better example in the README.

You're right there's probably a dozen different ways to achieve this. Home Assistant brings a lot of people together to contribute to open source, but it also brings together lots of different opinions of how things should be done, which leads to things being done many different ways sadly.

**Comment by jensrossbach** [comment]
@igorsantos07, @rianadon: For your information: this `last_action` attribute of scripts seems to be only useful if you did not provide an alias for the delay action because otherwise this attribute contains the alias text.

**Comment by rianadon** [comment]
Thanks for that! I'll have to update the card to work with the aliases. I hope that splitting on the last space would be enough to extract the time. E.g. `delay action alias 2:00:00` => `2:00:00`.

**Comment by jensrossbach** [comment]
In my test it was even worse, there was just the alias text but no delay value at all.

**Comment by rianadon** [comment]
That's too bad. So it looks like the only way this works is you don't rename your delay actions in the script editor.

**Comment by jensrossbach** [comment]
Yes, I think so. Maybe you could document this limitation to the README.
