### ISSUE TITLE
Round-up minutes

### ISSUE THREAD

**Issue by jensrossbach** [rianadon/timer-bar-card#86]
**Describe the bug**
When the resolution is configured to minutes, the minutes should be rounded up, e.g. if the remaining time is 20 minutes and 14 seconds, it should display 21 minutes, not 20 minutes. If the remaining time is less than a minute, this would correctly display 1 minute instead of nothing (current behavior).

**Your card configuration**
```yaml
type: custom:timer-bar-card
resolution: minutes
```

**Debug information**
Please add `debug: true` to your configuration and either take a screenshot or paste the output here!

**Comment by chriswood1001** [comment]
I second this. My timestamps happen to include seconds; however, I know it's realistically only accurate to the minute.

**Comment by rianadon** [comment]
You're right. That does make more sense than rounding down.
