### ISSUE TITLE
Mushroom "secondary_info:"

### ISSUE THREAD

**Issue by sippeeey** [rianadon/timer-bar-card#87]
Is it possible to add some other usefull infos, e.g. "secondary_info: last-changed" instead of the "state" --> (off).
![image](https://github.com/rianadon/timer-bar-card/assets/38763652/af028a8d-71c0-496f-87d2-f484fc75cc0c)

I am using the nice new mushroom timer cards and now it looks very good with my other cards. 👍

**Comment by rianadon** [comment]
Yes it's possible! This will be out in the next release.

> I am using the nice new mushroom timer cards and now it looks very good with my other cards. 👍

Thank you! I'm glad you like them!
