### ISSUE TITLE
input_number feature request

### ISSUE THREAD

**Issue by furstenbergs** [rianadon/timer-bar-card#9]
First of all, thanks for the awesome card!

I'm using it with my sprinkler system, however, my entities do not have any attributes. I set the sprinkler duration base on an "input_number" and then using automations to stop the sprinklers based on the value of the input_number. I'm trying to use the same input_number to set the fixed duration. For example:

```
type: custom:timer-bar-card
entities:
  - switch.garden_irrigation
duration:
  fixed: {{ states('input_number.garden_irrigation_timer') | int }}
```

Unfortunately, this does not seem to work. When going back into editing the card, it shows:

```
  fixed:
    '[object Object]': null
```

Any chance this can be supported in a future version of this card? Or if there is another way to achieve the same.

**Comment by rianadon** [comment]
Hahahaha nice try. Very creative. But no, this is not supported at the moment :(

I'm planning to support a `duration: { entity: 'input_number.garden_irrigation_timer' }` syntax later in a future version.
The wait is just because I'm trying to think of a better way to code this than the mess I had in mind.

Anyways, that will be happening soon. Otherwise, if you have nothing better to do the card will 100% work if you change your switches to timers and edit all your automations 🙃.

**Comment by furstenbergs** [comment]
Thanks for the feedback!

**Comment by rianadon** [comment]
One thing I've noticed while fixing some bugs: Currently the card expects durations to be in the format `00:10:00` = ten minutes.

Is your input_number in that format, or is it in a format like `10` = ten minutes?

**Comment by furstenbergs** [comment]
The input_number is just ```10```. Well, actually it is ```10.0``` that is why I need to convert it to an integer. 

However, I can do something like this to get it in ```hh:mm:ss``` format:

```
"00:{{ states('input_number.minutes') | int }}:00"
```

**Comment by rianadon** [comment]
Unfortunately I cannot figure out a way to make templates work inside a card. I think they're only a thing for automations / template entities. The plan is to add an extra `units` property for changing between hours/minutes/second/duration format.

**Comment by rianadon** [comment]
Let me know if you can achieve this in v1.6! You should be able to do something like:


```yaml
type: custom:timer-bar-card
entities:
  - switch.garden_irrigation
duration:
  entity: input_number.garden_irrigation_timer
  units: minutes
```

**Comment by furstenbergs** [comment]
Fantastic! Works like a charm. Thanks @rianadon
