### ISSUE TITLE
Display of Bar broken with layout: hide_name

### ISSUE THREAD

**Issue by MrFr33man123** [rianadon/timer-bar-card#90]
**Describe the bug**
The bar does not fill the width like it did before. the bar is just a few pixels wide. 
Before the bar spanned from the icon to the timer. 

**Your card configuration**
```yaml
type: custom:timer-bar-card
entity: timer.co2_buro
guess_mode: true
layout: hide_name
debug: true
...
```

**Debug information**
Please add `debug: true` to your configuration and either take a screenshot or paste the output here!
![Screenshot_20230627_061847_io homeassistant companion android](https://github.com/rianadon/timer-bar-card/assets/906150/2e9b1bb8-3ff6-40ea-bbd6-6a382bd6ead9)
![Screenshot_20230627_061441_io homeassistant companion android](https://github.com/rianadon/timer-bar-card/assets/906150/c2fe58cc-465a-4982-8020-fb9f370f1b7c)

Edit: seems like there is a class .info  and margin with ```flex: 1 1 30%;
margin-right: 16px;
margin-left: 8px;``` 

if i remove the whole info class it looks like before.

**Comment by rianadon** [comment]
Huh I'm not sure why that's happening. I'm viewing the card on 2023.6.3 and I don't notice any difference:

<img width="361" alt="image" src="https://github.com/rianadon/timer-bar-card/assets/18223213/49b31fc3-ba23-41ac-bd3a-e93696cec69b">

The `info` class is from the card, but if you remove the `flex` style the bar corrects itself?

**Comment by MrFr33man123** [comment]
In your Screenshot its clear that between Test and the bar there is a space. That space is extended when layout: hide_name is applyed also when the width of the card gets shrunk it gets to the point of not even beeing displayed at all.

And yes I removed the class .info in developer mode of the browser to check why it is happening.
![image](https://github.com/rianadon/timer-bar-card/assets/906150/2462a06d-f69e-4c68-b60b-8a5dd1d0d0d6)
This is full width.

![image](https://github.com/rianadon/timer-bar-card/assets/906150/26d817ba-803c-4cc0-961a-45a665da59f7)
This is shrunk => it even dissapears

![image](https://github.com/rianadon/timer-bar-card/assets/906150/cd05d54a-4dbd-4601-8451-f3e0780d4914)
This is small with the .info class removed.

![image](https://github.com/rianadon/timer-bar-card/assets/906150/cadd3da5-4a37-4457-9f91-9bb3289df975)
Removed that info in the div before the bar.

**Comment by rianadon** [comment]
Oh I see what happened now. https://github.com/rianadon/timer-bar-card/commit/28e679521f9d8127f6f35027268a5f8acf016f1c should have only added that `div` when the card when the timer is idle, but instead it always adds that `div`.
